from __future__ import annotations

from dataclasses import dataclass, asdict
from pathlib import Path
import hashlib
import json
import os
import re
import sqlite3
from typing import Iterable

from pypdf import PdfReader


MONEY_RE = re.compile(r"\b\d{1,4}\.\d{2}\b")
CODE_LINE_RE = re.compile(r"^([A-Z]{2,6}\d{0,3})\s+(.+)$")


@dataclass
class ScheduleProfile:
    """Dynamic profile of a schedule document generated by LLM analysis."""
    schedule_type: str  # "urgent_care", "rural", "gp", etc.
    description: str
    key_dimensions: list[str]  # ["location", "travel_time", "after_hours"]
    unique_rules: list[str]
    query_patterns: list[str]  # ["{specialty} consultation {location}"]
    example_queries: list[str]
    location_matters: bool
    mileage_reimbursable: bool
    after_hours_premium: bool


@dataclass
class IngestResult:
    source_path: str
    source_hash: str
    schedule_id: str
    text_output_path: str
    manifest_path: str
    db_path: str
    code_count: int
    indexed_chunks: int
    profile: ScheduleProfile


ANALYZE_SCHEDULE_PROMPT = """You are analyzing a medical fee schedule document.

DOCUMENT TEXT (first 8000 characters):
{text}

Analyze this schedule and respond with ONLY valid JSON. No markdown code blocks, no explanation, no text before or after the JSON.

Required JSON format:
{{
  "schedule_type": "rural",
  "description": "Rural practitioner schedule with travel modifiers",
  "key_dimensions": ["location", "travel_time", "mileage"],
  "unique_rules": ["Travel >20km bills separately"],
  "query_patterns": ["{{specialty}} {{location}}", "travel {{distance}}"],
  "example_queries": ["GP rural clinic", "travel 45km"],
  "location_matters": true,
  "mileage_reimbursable": true,
  "after_hours_premium": false
}}

Fields:
- schedule_type: Category like "urgent_care", "rural", "gp", "specialist", "hospital", "medical"
- description: Brief summary of what this schedule covers
- key_dimensions: List of factors that affect billing (location, time, age, etc.)
- unique_rules: Specific billing rules mentioned in the document
- query_patterns: Template patterns for searching this schedule
- example_queries: Example natural language queries
- location_matters: Whether location/venue affects pricing
- mileage_reimbursable: Whether travel distance is billable
- after_hours_premium: Whether after-hours premiums apply

IMPORTANT: Respond ONLY with the JSON object. No ```json markers, no explanations.
"""


def extract_json_from_llm_response(response: str) -> dict:
    """Extract and parse JSON from LLM response, handling various formats.
    
    Handles:
    - Markdown code blocks (```json...```)
    - Text before/after JSON
    - Single quotes instead of double quotes
    - Truncated or malformed JSON
    """
    import logging
    logger = logging.getLogger(__name__)
    
    if not response or not response.strip():
        raise ValueError("Empty response from LLM")
    
    response = response.strip()
    logger.debug(f"Raw LLM response (first 1000 chars): {response[:1000]}")
    logger.debug(f"Raw LLM response (last 500 chars): {response[-500:]}")
    
    # Try 1: Direct JSON parse
    try:
        return json.loads(response)
    except json.JSONDecodeError as e:
        logger.debug(f"Direct JSON parse failed: {e}")
        pass
    
    # Try 2: Extract from markdown code blocks
    markdown_patterns = [
        r'```json\s*\n(.*?)\n```',  # ```json ... ```
        r'```\s*\n(.*?)\n```',       # ``` ... ```
        r'`(.*?)`',                   # `...`
    ]
    
    for pattern in markdown_patterns:
        matches = re.findall(pattern, response, re.DOTALL)
        for match in matches:
            try:
                extracted = match.strip()
                logger.debug(f"Trying markdown extraction: {extracted[:200]}")
                return json.loads(extracted)
            except json.JSONDecodeError:
                continue
    
    # Try 3: Find JSON between first { and last }
    try:
        start_idx = response.find('{')
        end_idx = response.rfind('}')
        if start_idx != -1 and end_idx != -1 and end_idx > start_idx:
            json_str = response[start_idx:end_idx + 1]
            logger.debug(f"Trying brace extraction: {json_str[:200]}...{json_str[-100:]}")
            return json.loads(json_str)
    except json.JSONDecodeError as e:
        logger.debug(f"Brace extraction failed: {e}")
        pass
    
    # Try 4: Fix common issues - replace single quotes with double quotes
    try:
        # Replace single quotes with double quotes, but be careful with apostrophes
        fixed = response.replace("'", '"')
        # Try brace extraction again with fixed quotes
        start_idx = fixed.find('{')
        end_idx = fixed.rfind('}')
        if start_idx != -1 and end_idx != -1 and end_idx > start_idx:
            json_str = fixed[start_idx:end_idx + 1]
            logger.debug(f"Trying single-quote fix: {json_str[:200]}")
            return json.loads(json_str)
    except json.JSONDecodeError:
        pass
    
    # Try 5: Look for JSON-like structure with regex and clean it
    try:
        # Find anything that looks like a JSON object
        json_like = re.search(r'\{[\s\S]*\}', response)
        if json_like:
            json_str = json_like.group(0)
            # Remove trailing commas before closing braces/brackets
            json_str = re.sub(r',(\s*[}\]])', r'\1', json_str)
            logger.debug(f"Trying regex extraction with trailing comma fix: {json_str[:200]}")
            return json.loads(json_str)
    except json.JSONDecodeError:
        pass
    
    # Log the full response for debugging when all methods fail
    logger.error(f"All JSON extraction methods failed. Full response:\n{response}")
    raise ValueError(f"Could not extract valid JSON from LLM response. Response preview: {response[:500]}")


def validate_schedule_profile(profile: dict) -> tuple[bool, list[str]]:
    """Validate that the schedule profile has all required fields.
    
    Returns:
        tuple of (is_valid, list of missing fields)
    """
    required = ["schedule_type", "query_patterns", "key_dimensions"]
    missing = [field for field in required if field not in profile]
    return len(missing) == 0, missing


def _get_openai_client():
    api_key = os.getenv("OPENAI_API_KEY")
    if not api_key:
        return None
    try:
        from openai import OpenAI
        return OpenAI(api_key=api_key)
    except Exception:
        return None


def _create_generic_profile(reason: str = "Unknown") -> ScheduleProfile:
    """Create a generic fallback profile."""
    return ScheduleProfile(
        schedule_type="generic",
        description=f"Medical fee schedule (LLM analysis failed: {reason})",
        key_dimensions=["procedure", "provider_type"],
        unique_rules=[],
        query_patterns=["{procedure}", "{provider_type} consultation"],
        example_queries=["consultation", "procedure code"],
        location_matters=False,
        mileage_reimbursable=False,
        after_hours_premium=False,
    )


def _analyze_schedule_with_llm(text: str, model: str = "gpt-4o", max_retries: int = 3) -> ScheduleProfile:
    """Use LLM to analyze schedule and generate profile with retry logic."""
    import logging
    logger = logging.getLogger(__name__)
    
    client = _get_openai_client()
    
    # Truncate text to avoid token limits
    truncated = text[:8000]
    
    if client is None:
        logger.warning("No OpenAI client available, using generic profile")
        return _create_generic_profile("No API key")
    
    # Retry loop
    for attempt in range(max_retries):
        try:
            # Add stricter instruction on retries
            prompt = ANALYZE_SCHEDULE_PROMPT.format(text=truncated)
            if attempt > 0:
                prompt += f"\n\nATTEMPT {attempt + 1}/{max_retries}: You MUST respond with ONLY valid JSON. No markdown, no explanations."
            
            resp = client.chat.completions.create(
                model=model,
                temperature=0,
                response_format={"type": "json_object"},
                messages=[
                    {"role": "system", "content": prompt},
                ],
            )
            
            content = resp.choices[0].message.content
            
            # Extract JSON using robust extraction
            try:
                data = extract_json_from_llm_response(content)
                logger.debug(f"Successfully extracted JSON on attempt {attempt + 1}")
            except ValueError as e:
                logger.warning(f"JSON extraction failed on attempt {attempt + 1}: {e}")
                if attempt < max_retries - 1:
                    continue
                raise
            
            # Validate the profile
            is_valid, missing = validate_schedule_profile(data)
            if not is_valid:
                logger.warning(f"Profile validation failed on attempt {attempt + 1}. Missing fields: {missing}")
                if attempt < max_retries - 1:
                    continue
                # Last attempt: use what we have, fill in defaults
                logger.error(f"Using partial profile after {max_retries} failed attempts. Missing: {missing}")
            
            return ScheduleProfile(
                schedule_type=data.get("schedule_type", "generic"),
                description=data.get("description", "Medical fee schedule"),
                key_dimensions=data.get("key_dimensions", []),
                unique_rules=data.get("unique_rules", []),
                query_patterns=data.get("query_patterns", []),
                example_queries=data.get("example_queries", []),
                location_matters=data.get("location_matters", False),
                mileage_reimbursable=data.get("mileage_reimbursable", False),
                after_hours_premium=data.get("after_hours_premium", False),
            )
            
        except Exception as e:
            logger.error(f"LLM analysis error on attempt {attempt + 1}: {e}")
            if attempt < max_retries - 1:
                continue
            # Final attempt failed
            print(f"LLM analysis failed after {max_retries} attempts: {e}. Using generic profile.")
            return _create_generic_profile(str(e))
    
    # Should not reach here, but fallback just in case
    return _create_generic_profile("Max retries exceeded")


def sha256_file(path: Path) -> str:
    h = hashlib.sha256()
    with path.open("rb") as f:
        for chunk in iter(lambda: f.read(8192), b""):
            h.update(chunk)
    return h.hexdigest()


def _read_pages(pdf_path: Path) -> list[dict]:
    reader = PdfReader(str(pdf_path))
    pages = []
    for i, page in enumerate(reader.pages, start=1):
        pages.append({"page": i, "text": page.extract_text() or ""})
    return pages


def _normalise_lines(text: str) -> list[str]:
    return [ln.strip() for ln in text.splitlines() if ln.strip()]


def _parse_code_rows(lines: Iterable[str], page_num: int) -> list[dict]:
    """Parse code rows from schedule text. Generic parser that works across schedules."""
    rows: list[dict] = []
    lines = list(lines)
    i = 0
    while i < len(lines):
        m = CODE_LINE_RE.match(lines[i])
        if not m:
            i += 1
            continue

        code = m.group(1)
        first_part = m.group(2)
        desc_parts = [first_part]
        j = i + 1
        prices: list[float] = [float(v) for v in MONEY_RE.findall(first_part)]

        while j < len(lines):
            # New code row starts.
            if CODE_LINE_RE.match(lines[j]):
                break

            money = [float(v) for v in MONEY_RE.findall(lines[j])]
            if money:
                prices.extend(money)
            else:
                # Most rows have wrapped descriptions before price line appears.
                # Keep short, non-header text as description continuation.
                lower = lines[j].lower()
                if not lower.startswith(("code ", "page ", "per unit", "per hour", "flat rate", "schedule")):
                    desc_parts.append(lines[j])
            j += 1

        fee_excl = prices[0] if prices else None
        fee_incl = prices[1] if len(prices) > 1 else None

        description = " ".join(desc_parts).strip()
        description = re.sub(r"(?:\s+\d{1,4}\.\d{2}){1,4}\s*$", "", description).strip()

        rows.append(
            {
                "code": code,
                "description": description,
                "fee_excl_gst": fee_excl,
                "fee_incl_gst": fee_incl,
                "page": page_num,
            }
        )
        i = j
    return rows


def _init_db(db_path: Path) -> sqlite3.Connection:
    """Initialize SQLite database with generic schema."""
    db_path.parent.mkdir(parents=True, exist_ok=True)
    conn = sqlite3.connect(db_path)
    cur = conn.cursor()
    cur.execute(
        """
        CREATE TABLE IF NOT EXISTS schedule_versions (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            schedule_id TEXT UNIQUE,
            version TEXT,
            source_hash TEXT,
            source_path TEXT
        )
        """
    )
    cur.execute(
        """
        CREATE TABLE IF NOT EXISTS schedule_codes (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            schedule_id TEXT,
            code TEXT,
            description TEXT,
            fee_excl_gst REAL,
            fee_incl_gst REAL,
            page INTEGER,
            UNIQUE(schedule_id, code)
        )
        """
    )
    cur.execute(
        """
        CREATE TABLE IF NOT EXISTS policy_chunks (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            schedule_id TEXT,
            page INTEGER,
            chunk_text TEXT
        )
        """
    )
    cur.execute(
        """
        CREATE TABLE IF NOT EXISTS policy_chunk_embeddings (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            schedule_id TEXT,
            chunk_id INTEGER,
            embedding_json TEXT,
            UNIQUE(schedule_id, chunk_id)
        )
        """
    )
    conn.commit()
    return conn


def _chunk_text(text: str, max_words: int = 120) -> list[str]:
    words = text.split()
    if not words:
        return []
    out = []
    for i in range(0, len(words), max_words):
        out.append(" ".join(words[i : i + max_words]))
    return out


def _generate_embeddings(texts: Iterable[str], model: str = "text-embedding-3-small") -> list[list[float]]:
    """Generate embeddings for texts using OpenAI or fallback."""
    import numpy as np
    
    client = _get_openai_client()
    texts = list(texts)
    if not texts:
        return []

    if client is None:
        # Deterministic fallback pseudo-embedding for offline development.
        out = []
        for t in texts:
            vec = np.zeros(128, dtype=float)
            for token in t.lower().split():
                vec[hash(token) % 128] += 1.0
            n = np.linalg.norm(vec)
            out.append((vec / n).tolist() if n else vec.tolist())
        return out

    resp = client.embeddings.create(model=model, input=texts)
    return [d.embedding for d in resp.data]


def ingest_schedule(
    pdf_path: Path,
    schedule_id: str,  # e.g., "acc1520-medical", "acc1520-rural", "acc2024-gp"
    out_dir: Path,
    llm_model: str = "gpt-4o",
) -> IngestResult:
    """
    Generic schedule ingestion with dynamic profiling.
    
    Steps:
    1. Extract all text from PDF
    2. LLM analyzes document → generates ScheduleProfile
    3. Parse codes using profile guidance
    4. Generate embeddings
    5. Store: codes + embeddings + profile
    """
    # Setup output directory structure: data/processed/{schedule_id}/
    schedule_dir = out_dir / schedule_id
    schedule_dir.mkdir(parents=True, exist_ok=True)
    
    source_hash = sha256_file(pdf_path)
    pages = _read_pages(pdf_path)
    
    # Combine all text for LLM analysis
    full_text = "\n".join(p["text"] for p in pages)
    
    # Step 2: LLM analyzes document → generates ScheduleProfile
    profile = _analyze_schedule_with_llm(full_text, model=llm_model)
    
    # Save extracted text
    text_output = schedule_dir / f"{schedule_id}_text_pages.json"
    text_output.write_text(json.dumps(pages, ensure_ascii=False, indent=2))

    # Step 3: Parse codes
    code_rows: list[dict] = []
    for page in pages:
        lines = _normalise_lines(page["text"])
        code_rows.extend(_parse_code_rows(lines, page_num=page["page"]))

    # Deduplicate by code, keep latest occurrence.
    dedup = {row["code"]: row for row in code_rows}
    code_rows = list(dedup.values())

    # Step 4 & 5: Store in database
    db_path = schedule_dir / f"{schedule_id}.sqlite3"
    conn = _init_db(db_path)
    cur = conn.cursor()

    # Insert schedule version
    cur.execute(
        "INSERT OR REPLACE INTO schedule_versions(schedule_id, version, source_hash, source_path) VALUES (?, ?, ?, ?)",
        (schedule_id, schedule_id, source_hash, str(pdf_path)),
    )

    # Clear existing codes for this schedule
    cur.execute("DELETE FROM schedule_codes WHERE schedule_id = ?", (schedule_id,))
    for row in code_rows:
        cur.execute(
            """
            INSERT INTO schedule_codes(schedule_id, code, description, fee_excl_gst, fee_incl_gst, page)
            VALUES (?, ?, ?, ?, ?, ?)
            """,
            (
                schedule_id,
                row["code"],
                row["description"],
                row["fee_excl_gst"],
                row["fee_incl_gst"],
                row["page"],
            ),
        )

    # Clear existing chunks for this schedule
    cur.execute("DELETE FROM policy_chunks WHERE schedule_id = ?", (schedule_id,))
    chunk_rows = []
    for page in pages:
        for chunk in _chunk_text(page["text"], max_words=120):
            cur.execute(
                "INSERT INTO policy_chunks(schedule_id, page, chunk_text) VALUES (?, ?, ?)",
                (schedule_id, page["page"], chunk),
            )
            chunk_rows.append({"id": cur.lastrowid, "text": chunk})

    conn.commit()

    # Generate and store embeddings
    cur.execute("DELETE FROM policy_chunk_embeddings WHERE schedule_id = ?", (schedule_id,))
    
    texts = [r["text"] for r in chunk_rows]
    embeddings = _generate_embeddings(texts)
    
    for r, emb in zip(chunk_rows, embeddings):
        cur.execute(
            "INSERT INTO policy_chunk_embeddings(schedule_id, chunk_id, embedding_json) VALUES (?, ?, ?)",
            (schedule_id, r["id"], json.dumps(emb)),
        )

    conn.commit()
    conn.close()

    indexed_chunks = len(chunk_rows)

    # Save parsed codes as JSON
    parsed_json = schedule_dir / f"{schedule_id}_codes.json"
    parsed_json.write_text(json.dumps(code_rows, ensure_ascii=False, indent=2))

    # Create manifest with profile
    manifest = {
        "schedule_id": schedule_id,
        "source": str(pdf_path),
        "source_hash": source_hash,
        "pages": len(pages),
        "codes_parsed": len(code_rows),
        "chunks_indexed": indexed_chunks,
        "profile": asdict(profile),
        "artifacts": {
            "text_pages": str(text_output),
            "codes": str(parsed_json),
            "db": str(db_path),
        },
    }
    manifest_path = schedule_dir / "manifest.json"
    manifest_path.write_text(json.dumps(manifest, indent=2))

    return IngestResult(
        source_path=str(pdf_path),
        source_hash=source_hash,
        schedule_id=schedule_id,
        text_output_path=str(text_output),
        manifest_path=str(manifest_path),
        db_path=str(db_path),
        code_count=len(code_rows),
        indexed_chunks=indexed_chunks,
        profile=profile,
    )
